export enum MediaType {
	IMG = 'IMG',
	YOUTUBE_VIDEO = 'YOUTUBE_VIDEO',
	IMG_FILE = 'IMG_FILE',
	VIDEO_FILE = 'VIDEO_FILE',
	TEXT_FILE = 'TEXT_FILE',
	MP_LINK = 'MP_LINK',
	AUDIO_FILE = 'AUDIO_FILE'
}
